package com.yzx.elec.pojo;

// Generated 2016-4-19 15:13:58 by Hibernate Tools 3.4.0.CR1

/**
 * ElecSystemddl generated by hbm2java
 */
@SuppressWarnings("serial")
public class ElecSystemDDL implements java.io.Serializable {

	private int seqId;
	private String keyword;
	private int ddlCode;
	private String ddlname;

	public ElecSystemDDL() {
	}

	public ElecSystemDDL(int seqId, String keyword, int ddlCode, String ddlname) {
		this.seqId = seqId;
		this.keyword = keyword;
		this.ddlCode = ddlCode;
		this.ddlname = ddlname;
	}

	public int getSeqId() {
		return this.seqId;
	}

	public void setSeqId(int seqId) {
		this.seqId = seqId;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public int getDdlCode() {
		return this.ddlCode;
	}

	public void setDdlCode(int ddlCode) {
		this.ddlCode = ddlCode;
	}

	public String getDdlname() {
		return this.ddlname;
	}

	public void setDdlname(String ddlname) {
		this.ddlname = ddlname;
	}

}
