package com.yzx.elec.pojo;

// Generated 2016-4-19 15:13:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ElecUser generated by hbm2java
 */
@SuppressWarnings("serial")
public class ElecUser implements java.io.Serializable {

	private String userId;
	private String jctId;
	private String userName;
	private String logonName;
	private String logonPassword;
	private String sexId;
	private Date birthDay;
	private String address;
	private String contactTel;
	private String email;
	private String mobile;
	private String isDuty;
	private Date onDutyDate;
	private Date offDutyDate;
	private String remark;

	public ElecUser() {
	}

	public ElecUser(String userId, String jctId, String userName,
			String logonName, String logonPassword, String sexId) {
		this.userId = userId;
		this.jctId = jctId;
		this.userName = userName;
		this.logonName = logonName;
		this.logonPassword = logonPassword;
		this.sexId = sexId;
	}

	public ElecUser(String userId, String jctId, String userName,
			String logonName, String logonPassword, String sexId,
			Date birthDay, String address, String contactTel, String email,
			String mobile, String isDuty, Date onDutyDate, Date offDutyDate,
			String remark) {
		this.userId = userId;
		this.jctId = jctId;
		this.userName = userName;
		this.logonName = logonName;
		this.logonPassword = logonPassword;
		this.sexId = sexId;
		this.birthDay = birthDay;
		this.address = address;
		this.contactTel = contactTel;
		this.email = email;
		this.mobile = mobile;
		this.isDuty = isDuty;
		this.onDutyDate = onDutyDate;
		this.offDutyDate = offDutyDate;
		this.remark = remark;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getJctId() {
		return this.jctId;
	}

	public void setJctId(String jctId) {
		this.jctId = jctId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLogonName() {
		return this.logonName;
	}

	public void setLogonName(String logonName) {
		this.logonName = logonName;
	}

	public String getLogonPassword() {
		return this.logonPassword;
	}

	public void setLogonPassword(String logonPassword) {
		this.logonPassword = logonPassword;
	}

	public String getSexId() {
		return this.sexId;
	}

	public void setSexId(String sexId) {
		this.sexId = sexId;
	}

	public Date getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getIsDuty() {
		return this.isDuty;
	}

	public void setIsDuty(String isDuty) {
		this.isDuty = isDuty;
	}

	public Date getOnDutyDate() {
		return this.onDutyDate;
	}

	public void setOnDutyDate(Date onDutyDate) {
		this.onDutyDate = onDutyDate;
	}

	public Date getOffDutyDate() {
		return this.offDutyDate;
	}

	public void setOffDutyDate(Date offDutyDate) {
		this.offDutyDate = offDutyDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
