package com.yzx.elec.pojo;

// Generated 2016-4-19 15:13:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ElecText generated by hbm2java
 */
@SuppressWarnings("serial")
public class ElecText implements java.io.Serializable {

	private String elecid;
	private String elecname;
	private Date electime;
	private String elecremark;
	private String textid;
	private String textname;
	private Date textdate;
	private String textremark;

	public ElecText() {
	}

	public ElecText(String elecid, String elecname) {
		this.elecid = elecid;
		this.elecname = elecname;
	}

	public ElecText(String elecid, String elecname, Date electime,
			String elecremark, String textid, String textname, Date textdate,
			String textremark) {
		this.elecid = elecid;
		this.elecname = elecname;
		this.electime = electime;
		this.elecremark = elecremark;
		this.textid = textid;
		this.textname = textname;
		this.textdate = textdate;
		this.textremark = textremark;
	}

	public String getElecid() {
		return this.elecid;
	}

	public void setElecid(String elecid) {
		this.elecid = elecid;
	}

	public String getElecname() {
		return this.elecname;
	}

	public void setElecname(String elecname) {
		this.elecname = elecname;
	}

	public Date getElectime() {
		return this.electime;
	}

	public void setElectime(Date electime) {
		this.electime = electime;
	}

	public String getElecremark() {
		return this.elecremark;
	}

	public void setElecremark(String elecremark) {
		this.elecremark = elecremark;
	}

	public String getTextid() {
		return this.textid;
	}

	public void setTextid(String textid) {
		this.textid = textid;
	}

	public String getTextname() {
		return this.textname;
	}

	public void setTextname(String textname) {
		this.textname = textname;
	}

	public Date getTextdate() {
		return this.textdate;
	}

	public void setTextdate(Date textdate) {
		this.textdate = textdate;
	}

	public String getTextremark() {
		return this.textremark;
	}

	public void setTextremark(String textremark) {
		this.textremark = textremark;
	}

}
