package com.yzx.elec.pojo;
// Generated 2016-2-12 0:14:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ElecCommonmsg generated by hbm2java
 */
public class ElecCommonMsg implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long comId;
	private String stationRun;
	private String devRun;
	private Date createDate;

	public ElecCommonMsg() {
	}

	public Long getComId() {
		return this.comId;
	}

	public void setComId(Long comId) {
		this.comId = comId;
	}

	public String getStationRun() {
		return this.stationRun;
	}

	public void setStationRun(String stationRun) {
		this.stationRun = stationRun;
	}

	public String getDevRun() {
		return this.devRun;
	}

	public void setDevRun(String devRun) {
		this.devRun = devRun;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
