package com.yzx.elec.pojo;

// Generated 2016-4-29 17:14:37 by Hibernate Tools 3.4.0.CR1

/**
 * ElecUserRole generated by hbm2java
 */
@SuppressWarnings("serial")
public class ElecUserRole implements java.io.Serializable {

	private Integer seqId;
	private int userId;
	private int roleId;
	private String remark;

	public ElecUserRole() {
	}

	public ElecUserRole(int userId, int roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public ElecUserRole(int userId, int roleId, String remark) {
		this.userId = userId;
		this.roleId = roleId;
		this.remark = remark;
	}

	public Integer getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
