package com.yzx.elec.pojo;

// Generated 2016-6-24 18:42:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ElecLog generated by hbm2java
 */
public class ElecLog implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer logId;
	private String opreateName;
	private Date opreateDate;
	private String detail;

	public ElecLog() {
	}

	public ElecLog(String opreateName, Date opreateDate) {
		this.opreateName = opreateName;
		this.opreateDate = opreateDate;
	}

	public ElecLog(String opreateName, Date opreateDate, String detail) {
		this.opreateName = opreateName;
		this.opreateDate = opreateDate;
		this.detail = detail;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public String getOpreateName() {
		return this.opreateName;
	}

	public void setOpreateName(String opreateName) {
		this.opreateName = opreateName;
	}

	public Date getOpreateDate() {
		return this.opreateDate;
	}

	public void setOpreateDate(Date opreateDate) {
		this.opreateDate = opreateDate;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
