package com.yzx.elec.pojo;

// Generated 2016-4-29 17:13:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ElecCommonmsg generated by hbm2java
 */
@SuppressWarnings("serial")
public class ElecCommonMsg implements java.io.Serializable {

	private int comId;
	private String stationRun;
	private String devRun;
	private Date createDate;

	public ElecCommonMsg() {
	}

	public ElecCommonMsg(int comId) {
		this.comId = comId;
	}

	public ElecCommonMsg(int comId, String stationRun, String devRun,
			Date createDate) {
		this.comId = comId;
		this.stationRun = stationRun;
		this.devRun = devRun;
		this.createDate = createDate;
	}

	public int getComId() {
		return this.comId;
	}

	public void setComId(int comId) {
		this.comId = comId;
	}

	public String getStationRun() {
		return this.stationRun;
	}

	public void setStationRun(String stationRun) {
		this.stationRun = stationRun;
	}

	public String getDevRun() {
		return this.devRun;
	}

	public void setDevRun(String devRun) {
		this.devRun = devRun;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
