package com.yzx.elec.web.form;

// Generated 2016-6-24 18:42:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ElecLog generated by hbm2java
 */
public class ElecLogForm {
	private Integer logId;
	private String ipAddress;
	private String opreateName;
	private String opreateDate;
	private String detail;

	public ElecLogForm() {
	}


	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getOpreateName() {
		return this.opreateName;
	}

	public void setOpreateName(String opreateName) {
		this.opreateName = opreateName;
	}

	public String getOpreateDate() {
		return this.opreateDate;
	}

	public void setOpreateDate(String opreateDate) {
		this.opreateDate = opreateDate;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
