package com.yzx.elec.web.form;
// Generated 2016-2-7 17:34:58 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ElecText generated by hbm2java
 */
public class ElecMenuForm {

	private String textname;
	private Date textdate;
	private String textremark;

	public ElecMenuForm() {
	}

	public String getTextname() {
		return this.textname;
	}

	public void setTextname(String textname) {
		this.textname = textname;
	}

	public Date getTextdate() {
		return this.textdate;
	}

	public void setTextdate(Date textdate) {
		this.textdate = textdate;
	}

	public String getTextremark() {
		return this.textremark;
	}

	public void setTextremark(String textremark) {
		this.textremark = textremark;
	}

}
