package com.yzx.elec.web.form;
// Generated 2016-2-7 17:34:58 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ElecText generated by hbm2java
 */
public class ElecMenuForm {

	private String textname;
	private Date textdate;
	private String textremark;
	
	/**
	 * 登录名
	 */
	private String name;
	/**
	 * 登陆密码
	 */
	private String password;
	
	/**
	 * 验证码
	 */
	private String checkWord;
	
	/**
	 * 是否记住
	 */
	private String remeberMe;

	public ElecMenuForm() {
	}

	public String getTextname() {
		return this.textname;
	}

	public void setTextname(String textname) {
		this.textname = textname;
	}

	public Date getTextdate() {
		return this.textdate;
	}

	public void setTextdate(Date textdate) {
		this.textdate = textdate;
	}

	public String getTextremark() {
		return this.textremark;
	}

	public void setTextremark(String textremark) {
		this.textremark = textremark;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCheckWord() {
		return checkWord;
	}

	public void setCheckWord(String checkWord) {
		this.checkWord = checkWord;
	}

	public String getRemeberMe() {
		return remeberMe;
	}

	public void setRemeberMe(String remeberMe) {
		this.remeberMe = remeberMe;
	}

}
